apiVersion: v1
kind: Service
metadata:
  name: email-validator-service
spec:
  selector:
    app: email-validator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
