name: Upload Static Frontend to S3

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/main/resources/static/**'

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload static frontend to S3
      run: |
        BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
        aws s3 sync src/main/resources/static s3://$BUCKET_NAME/ --delete --acl public-read
